name: flutter_gruvbox_theme
description: Retro groove theme for Flutter, based on the Gruvbox color scheme.
version: 2.1.0
repository: https://github.com/pablojimpas/flutter_gruvbox_theme

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: '>=1.17.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
    
  flutter_lints: ^1.0.0

flutter:
