name: full_example
description: Full example app showcasing the Gruvbox Theme for Flutter.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_gruvbox_theme:
    path: ../../

dev_dependencies:
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true